[ramya_logs]
retentionTime = 2
homePath = $SPLUNK_DB/ramya_logs/db
coldPath = $SPLUNK_DB/ramya_logs/colddb
thawedPath = $SPLUNK_DB/ramya_logs/thaweddb
maxDataSize = 

==================================================

